project/blog/models.py
from datetime import datetime

from project import db


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer(), primary_key=True)
    text = db.Column(db.Text, nullable=False)
    created_on = db.Column(db.DateTime(), default=datetime.utcnow)
    updated_on = db.Column(
        db.DateTime(), default=datetime.utcnow,  onupdate=datetime.utcnow)
    author_id = db.Column(
        db.Integer(), db.ForeignKey('users.id'), nullable=False)
    favorites = db.relationship(
        'Favorite', backref='post', cascade='all,delete-orphan')
    comments = db.relationship(
        'Comment', backref='post', cascade='all,delete-orphan')

    def __repr__(self):
        return "<Post:{}>".format(self.text[:10])


class Favorite(db.Model):
    __tablename__ = 'favorites'
    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(
        db.Integer(), db.ForeignKey('users.id'), nullable=False)
    post_id = db.Column(
        db.Integer(), db.ForeignKey('posts.id'), nullable=False)


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer(), primary_key=True)
    text = db.Column(db.Text, nullable=False)
    created_on = db.Column(db.DateTime(), default=datetime.utcnow)
    updated_on = db.Column(
        db.DateTime(), default=datetime.utcnow,  onupdate=datetime.utcnow)
    author_id = db.Column(
        db.Integer(), db.ForeignKey('users.id'), nullable=False)
    post_id = db.Column(
        db.Integer(), db.ForeignKey('posts.id'), nullable=False)

    def __repr__(self):
        return "<Comment:{}>".format(self.text[:10])

project/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    text = TextAreaField('Текст', validators=[DataRequired()])


class CommentForm(FlaskForm):
    text = TextAreaField('Текст', validators=[DataRequired()])

project/__init__.py
import datetime as dt
import locale

from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

LOGIN = 'Пожалуйста, авторизуйтесь, чтобы получить доступ к этой странице'

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.login_message = LOGIN
locale.setlocale(locale.LC_ALL, 'ru-Ru')


def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = 'secret-key-goes-here'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    migrate.init_app(app,  db)
    login_manager.init_app(app)

    from .auth.views import bp as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .blog.views import bp as blog_blueprint
    app.register_blueprint(blog_blueprint)

    @app.context_processor
    def year():
        return {'year': dt.date.today().year}

    return app

project/blog/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from project import db
from project.auth.models import User
from .forms import CommentForm, PostForm
from .models import Comment, Favorite, Post

POST_DELETED = 'Запись удалена'
FAVORITE_EXISTS = 'Запись уже в избранном'
FAVORITE_NOT_EXISTS = 'Запись отсутствует в избранном'
COMMENT_DELETED = 'Комментарий удалён'

bp = Blueprint('blog', __name__)


@bp.route('/')
def index():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('blog/index.html', posts=posts)


@bp.route('/posts', methods=('GET', 'POST'), strict_slashes=False)
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(text=form.text.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('.post_detail', id=post.id))
    return render_template('blog/create_post.html', form=form)


@bp.route('/posts/<int:id>/edit', methods=('GET', 'POST'),
          strict_slashes=False)
@login_required
def update_post(id):
    post = Post.query.get_or_404(id)
    if post.author != current_user:
        return redirect(url_for('.post_detail', id=id))
    form = PostForm(text=post.text)
    if form.validate_on_submit():
        post.text = form.text.data
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('.post_detail', id=id))
    return render_template('blog/create_post.html', form=form)


@bp.route('/posts/<int:id>/delete', strict_slashes=False)
@login_required
def delete_post(id):
    post = Post.query.get_or_404(id)
    if post.author != current_user:
        return redirect(url_for('.post_detail', id=id))
    db.session.delete(post)
    db.session.commit()
    flash(POST_DELETED)
    return redirect(url_for('.index'))


@bp.route('/posts/<int:id>', strict_slashes=False)
def post_detail(id, form=None, comment_id=None):
    post = Post.query.get_or_404(id)
    favorite = current_user.is_authenticated and Favorite.query.filter_by(
        post=post, user=current_user).first() is not None
    count = Favorite.query.filter_by(post=post).count()
    comments = Comment.query.filter_by(post=post).all()
    form = CommentForm() if form is None else form
    return render_template(
        'blog/post_detail.html', post=post, favorite=favorite, count=count,
        comments=comments, form=form, comment_id=comment_id)


@bp.route('/profile/<string:username>', strict_slashes=False)
def profile(username):
    author = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=author).order_by(Post.id.desc()).all()
    return render_template('blog/profile.html', author=author, posts=posts)


@bp.route('/posts/<int:id>/like', strict_slashes=False)
@login_required
def add_favorite(id):
    post = Post.query.get_or_404(id)
    if Favorite.query.filter_by(post=post, user=current_user).first():
        flash(FAVORITE_EXISTS)
        return redirect(url_for('.post_detail', id=id))
    favorite = Favorite(post=post, user=current_user)
    db.session.add(favorite)
    db.session.commit()
    return redirect(url_for('.post_detail', id=id))


@bp.route('/posts/<int:id>/dislike', strict_slashes=False)
@login_required
def delete_favorite(id):
    post = Post.query.get_or_404(id)
    favorite = Favorite.query.filter_by(post=post, user=current_user).first()
    if favorite is None:
        flash(FAVORITE_NOT_EXISTS)
        return redirect(url_for('.post_detail', id=id))
    db.session.delete(favorite)
    db.session.commit()
    return redirect(url_for('.post_detail', id=id))


@bp.route('/favorites', strict_slashes=False)
@login_required
def favorites():
    posts = Post.query.filter(Post.favorites.any(
        Favorite.user == current_user)).order_by(Post.id.desc()).all()
    return render_template('blog/favorites.html', posts=posts)


@bp.route('/posts/<int:id>/comments', methods=('POST',), strict_slashes=False)
@login_required
def add_comment(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(text=form.text.data, author=current_user, post=post)
        db.session.add(comment)
        db.session.commit()
    return redirect(url_for('.post_detail', id=id))


@bp.route('/posts/<int:id>/comments/<int:comment_id>/edit',
          methods=('GET', 'POST'), strict_slashes=False)
@login_required
def update_comment(id, comment_id):
    Post.query.get_or_404(id)
    comment = Comment.query.get_or_404(comment_id)
    if comment.author != current_user:
        return redirect(url_for('.post_detail', id=id))
    form = CommentForm(text=comment.text)
    if form.validate_on_submit():
        comment.text = form.text.data
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('.post_detail', id=id))
    return post_detail(id=id, form=form, comment_id=comment_id)


@bp.route('/posts/<int:id>/comments/<int:comment_id>/delete',
          strict_slashes=False)
@login_required
def delete_comment(id, comment_id):
    Post.query.get_or_404(id)
    comment = Comment.query.get_or_404(comment_id)
    if comment.author != current_user:
        return redirect(url_for('.post_detail', id=id))
    db.session.delete(comment)
    db.session.commit()
    flash(COMMENT_DELETED)
    return redirect(url_for('.post_detail', id=id))

project/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content%}{% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

project/templates/blog/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if request.endpoint == 'blog.create_post' %}
    Новая запись
  {% else %}
    Редактировать запись
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-5 p-3">
      <div class="card">
        <div class="card-header">
          {% if request.endpoint == 'blog.create_post' %}
            Новая запись
          {% else %}
            Редактировать запись
          {% endif %}
        </div>
        <div class="card-body">
          <form action="" method="post">
            {% include 'includes/errors.html' %}
            {{ form.csrf_token() }}
            <div class="form-group my-3">
              {{ form.text.label() }}
              {{ form.text(class="form-control") }}
              {% for error in form.text.errors %}
                <div class="alert alert-danger">{{ error }}</div>
              {% endfor %}
            </div>
            <div class="col-md-6">
              <button type="submit" class="btn btn-primary">
                {% if request.endpoint == 'blog.create_post' %}
                  Создать
                {% else %}
                  Сохранить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

project/templates/blog/favorites.html
{% extends 'base.html' %}
{% block title %}Избранное{% endblock %}
{% block content %}
  <h3 class="border-top text-center py-3">Любимые записи</h3>
  <hr>
  {% include 'includes/errors.html' %}
  {% include 'blog/includes/post_loop.html' %}
{% endblock %} 

project/templates/blog/includes/comments.html
{% if current_user.is_authenticated %}
  <div class="col-md-5 ">
    <div class="card my-4">
      <h5 class="card-header">
        {% if not comment_id %}
          Добавить комментарий:
        {% else %}
          Редактировать комментарий:
        {% endif %}
      </h5>
      <div class="card-body">
        <form method="post"
          {% if not comment_id %}
            action="{{ url_for('blog.add_comment', id=post.id) }}"
          {% else %}
            action="{{ url_for('blog.update_comment', id=post.id, comment_id=comment_id) }}"
          {% endif %}
        >
          {{ form.csrf_token() }}      
          <div class="form-group mb-2">
            {{ form.text(class="form-control") }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      </div>
    </div>
  </div>
{% endif %}
<h5 class="card-header">Комментарии:</h5>
<div class="card-body">
  {% for comment in comments %}
    <div class="media mb-4">
      <div class="media-body">
        <h5 class="mt-0">
          <a href="{{ url_for('blog.profile', username=comment.author.username) }}">
            {{ comment.author.first_name | capitalize }}
            {{ comment.author.last_name | capitalize }}
          </a>
        </h5>
        <p>{{ comment.text }}</p>
        {% if comment.author == current_user %}
          <a href="{{ url_for('blog.update_comment', id=post.id, comment_id=comment.id)}}">редактировать</a>
          или
          <a href="{{ url_for('blog.delete_comment', id=post.id, comment_id=comment.id)}}">удалить</a>
        {% endif %}
      </div>
    </div>
    {% if not loop.last %}<hr>{% endif %}
  {% endfor %}
</div>

project/templates/blog/includes/post_loop.html
{% for post in posts %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      {% if request.endpoint != 'blog.profile' %}
        <li class="list-group-item">
          Автор: <a href="{{ url_for('blog.profile', username=post.author.username) }}">
          {{ post.author.first_name | capitalize}} {{ post.author.last_name | capitalize }}</a>
        </li>
      {% endif %}
      <li class="list-group-item">
        Дата публикации: {{ post.created_on.strftime('%d %B %Y') }} 
      </li>
      <li class="list-group-item">
        <a href="{{ url_for('blog.post_detail', id=post.id) }}">
          подробная информация
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>{{ post.text }}</p>
  </article>  
  {% if not loop.last %}<hr>{% endif %}
  <br>
</div>
{% endfor %}

project/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <h3 class="border-top text-center py-3">Лента сообщений</h3>
  <hr>
  {% include 'includes/errors.html' %}
  {% include 'blog/includes/post_loop.html' %}
{% endblock %} 

project/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %}{{ post.text[:15] }}{% endblock %}
{% block content %}
<h3 class="border-top text-center py-3">Подробная информация</h3>
  <hr>
  {% include 'includes/errors.html' %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Автор: <a href="{{ url_for('blog.profile', username = post.author.username) }}">
          {{ post.author.first_name }} {{post.author.last_name}}</a>
        </li>
        <li class="list-group-item">
          Дата публикации: {{ post.created_on.strftime('%d %B %Y') }} 
        </li>
        <li class="list-group-item">
          Дата последнего изменения: {{ post.updated_on.strftime('%d %B %Y') }} 
        </li>
        <li class="list-group-item">
          Добавлений в избранное: {{ count }} 
        </li>
        {% if current_user.is_authenticated %}
          <li class="list-group-item">
            {% if not favorite %}
              <a class="btn btn-lg btn-primary" href="{{ url_for('blog.add_favorite', id=post.id) }}" role="button">
                В избранное
              </a>
            {% else %}
              <a class="btn btn-lg btn-light" href="{{ url_for('blog.delete_favorite', id=post.id) }}" role="button">
                Из избранного
              </a>
            {% endif %}
          </li>
        {% endif %}
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>{{ post.text }}</p>
      {% if post.author == current_user %}  
            <a class="btn btn-primary" href="{{ url_for('blog.update_post', id=post.id) }}">редактировать</a>
            <a class="btn btn-primary" href="{{ url_for('blog.delete_post', id=post.id) }}" >удалить</a>
      {% endif %}
      {% include 'blog/includes/comments.html' %}
    </article>  
  </div>
{% endblock %} 

project/templates/blog/profile.html
{% extends 'base.html' %}
{% block title %}{{ author.username }}{% endblock %}
{% block content %}
<h3 class="border-top text-center py-3">Записи пользователя {{ author.first_name }} {{ author.last_name }}</h3>
  <hr>
  {% include 'includes/errors.html' %}
  {% include 'blog/includes/post_loop.html' %}
{% endblock %} 

project/templates/includes/errors.html
{% for message in get_flashed_messages() %}
  <div class="alert alert-danger">{{ message }}</div>
{% endfor %}

project/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Flask</span> project</p>

project/templates/includes/form_errors.html
{% for message in get_flashed_messages() %}
  <div class="alert alert-danger">{{ message }}</div>
{% endfor %}

project/templates/includes/form_loop.html
{% for field in form if field.name != 'csrf_token' %}
<div class="form-group my-3">
  {{ field.label() }}
  {{ field(class="form-control") }}
  {% for error in field.errors %}
    <div class="alert alert-danger">{{ error }}</div>
  {% endfor %}
</div>
{% endfor %}

project/templates/includes/header.html
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('blog.index')}}">
        <span style="color:red">Flask</span> project
      </a>
      <ul class="nav nav-pills">
        {% if current_user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{{ url_for('blog.favorites') }}">Избранное</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{{ url_for('blog.create_post') }}">Создать запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{{ url_for('auth.logout')}}?next={{ request.path }}">Выйти</a>
          </li>
          <li class="nav-link"> 
            {{ current_user.username | capitalize }}
          </li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{{ url_for('auth.login')}}?next={{ request.path }}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{{ url_for('auth.signup')}}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>